//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeartValve.Shared.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int InventoryID { get; set; }
        public int EquipTypeID { get; set; }
        public string Manufacturer { get; set; }
        public string SerialNo { get; set; }
        public string ModelNo { get; set; }
        public Nullable<int> PurchaserID { get; set; }
        public string MacAddr { get; set; }
        public Nullable<System.DateTime> AcqDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> RetiredDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string PhoneNo { get; set; }
        public string BluetoothModelNo { get; set; }
        public Nullable<int> BPMCuffSizeID { get; set; }
    }
}
